// SPDX-License-Identifier: Unlicense OR MIT

// Command assets converts data files to Go source code.
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "please specify a directory to convert")
		os.Exit(1)
	}
	dir := os.Args[1]
	pkgName := filepath.Base(dir)
	var w bytes.Buffer
	w.WriteString("// Code generated by command assets DO NOT EDIT.\n\n")
	fmt.Fprintf(&w, "package %s\n\n", pkgName)
	filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		if filepath.Ext(path) == ".go" {
			return nil
		}
		name := path[len(dir):]
		name = strings.ReplaceAll(name, "/", "_")
		name = strings.ReplaceAll(name, ".", "_")
		name = strings.ReplaceAll(name, "-", "_")
		name = strings.Title(name)
		content, err := ioutil.ReadFile(path)
		if err != nil {
			return err
		}
		fmt.Fprintf(&w, "var %s = %#v\n", name, content)
		return nil
	})
	err := ioutil.WriteFile(filepath.Join(dir, "assets.go"), w.Bytes(), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
}
